import { Client, Priority, Status, Task, Team } from './types';

export const MOCK_CLIENTS: Client[] = [
  {
    id: 'c1',
    name: 'Bridgewater',
    industry: 'Financial Services',
    contactPerson: 'James Bridge',
    email: 'james@bridgewater.com',
    status: 'Active',
    avatarUrl: 'https://ui-avatars.com/api/?name=Bridgewater&background=0D8ABC&color=fff',
  },
  {
    id: 'c2',
    name: 'Lets Fade',
    industry: 'Grooming & Lifestyle',
    contactPerson: 'Marcus Fade',
    email: 'marcus@letsfade.com',
    status: 'Active',
    avatarUrl: 'https://ui-avatars.com/api/?name=Lets+Fade&background=10b981&color=fff',
  },
  {
    id: 'c3',
    name: 'AudioPro',
    industry: 'Audio Equipment',
    contactPerson: 'Sarah Sound',
    email: 'sarah@audiopro.com',
    status: 'Active',
    avatarUrl: 'https://ui-avatars.com/api/?name=Audio+Pro&background=6366f1&color=fff',
  },
  {
    id: 'c4',
    name: 'Neonlight',
    industry: 'Lighting & Decor',
    contactPerson: 'Leo Neon',
    email: 'leo@neonlight.com',
    status: 'Active',
    avatarUrl: 'https://ui-avatars.com/api/?name=Neonlight&background=f59e0b&color=fff',
  },
  {
    id: 'c5',
    name: 'WeCare',
    industry: 'Healthcare',
    contactPerson: 'Dr. Emily',
    email: 'emily@wecare.com',
    status: 'Active',
    avatarUrl: 'https://ui-avatars.com/api/?name=WeCare&background=ef4444&color=fff',
  },
  {
    id: 'c6',
    name: 'Al Sarab Cafe',
    industry: 'Hospitality',
    contactPerson: 'Ahmed',
    email: 'manager@alsarab.com',
    status: 'Active',
    avatarUrl: 'https://ui-avatars.com/api/?name=Al+Sarab&background=8b5cf6&color=fff',
  },
  {
    id: 'c7',
    name: 'Tonio & Senora',
    industry: 'Fashion Retail',
    contactPerson: 'Antonio',
    email: 'info@tonioandsenora.com',
    status: 'Active',
    avatarUrl: 'https://ui-avatars.com/api/?name=Tonio+Senora&background=ec4899&color=fff',
  },
  {
    id: 'c8',
    name: 'Lamplus',
    industry: 'Interior Design',
    contactPerson: 'Lana Lamp',
    email: 'lana@lamplus.com',
    status: 'Onboarding',
    avatarUrl: 'https://ui-avatars.com/api/?name=Lamplus&background=14b8a6&color=fff',
  },
  {
    id: 'c9',
    name: 'Zappo',
    industry: 'E-commerce',
    contactPerson: 'Zach',
    email: 'zach@zappo.com',
    status: 'Active',
    avatarUrl: 'https://ui-avatars.com/api/?name=Zappo&background=f97316&color=fff',
  },
  {
    id: 'c10',
    name: 'Styleloom',
    industry: 'Fashion',
    contactPerson: 'Stella',
    email: 'stella@styleloom.com',
    status: 'Active',
    avatarUrl: 'https://ui-avatars.com/api/?name=Styleloom&background=84cc16&color=fff',
  },
  {
    id: 'c11',
    name: 'Tangan Furniture',
    industry: 'Furniture',
    contactPerson: 'Tan',
    email: 'tan@tangan.com',
    status: 'Active',
    avatarUrl: 'https://ui-avatars.com/api/?name=Tangan&background=a855f7&color=fff',
  },
  {
    id: 'c12',
    name: 'MO Clinic',
    industry: 'Medical Aesthetics',
    contactPerson: 'Dr. Mo',
    email: 'contact@moclinic.com',
    status: 'Active',
    avatarUrl: 'https://ui-avatars.com/api/?name=MO+Clinic&background=06b6d4&color=fff',
  },
  {
    id: 'c13',
    name: 'synops labs',
    industry: 'Technology',
    contactPerson: 'Sy',
    email: 'sy@synopslabs.com',
    status: 'Onboarding',
    avatarUrl: 'https://ui-avatars.com/api/?name=Synops&background=64748b&color=fff',
  },
];

export const MOCK_TASKS: Task[] = [
  // AudioPro - website pending
  {
    id: 't1',
    clientId: 'c3',
    title: 'Website Development',
    description: 'Complete website overhaul and launch.',
    status: Status.PENDING,
    priority: Priority.HIGH,
    team: Team.DEV,
    dueDate: '2025-05-20',
    assignedTo: 'Dev Team',
  },
  // Neonlight - Google ads optimization
  {
    id: 't2',
    clientId: 'c4',
    title: 'Google Ads Optimization',
    description: 'Optimize keywords and bid strategy for Q2.',
    status: Status.IN_PROGRESS,
    priority: Priority.HIGH,
    team: Team.MARKETING,
    dueDate: '2025-05-15',
    assignedTo: 'Marketing Lead',
  },
  // Lamplus - website
  {
    id: 't3',
    clientId: 'c8',
    title: 'New Website Launch',
    description: 'Finalize design and implement frontend.',
    status: Status.PENDING,
    priority: Priority.CRITICAL,
    team: Team.DEV,
    dueDate: '2025-06-01',
    assignedTo: 'Frontend Dev',
  },
  // Zappo - shopify optimization, run ads
  {
    id: 't4',
    clientId: 'c9',
    title: 'Shopify Optimization',
    description: 'Improve page load speed and checkout flow.',
    status: Status.IN_PROGRESS,
    priority: Priority.MEDIUM,
    team: Team.DEV,
    dueDate: '2025-05-25',
    assignedTo: 'Shopify Expert',
  },
  {
    id: 't5',
    clientId: 'c9',
    title: 'Launch Ad Campaign',
    description: 'Setup and run new seasonal marketing ads.',
    status: Status.PENDING,
    priority: Priority.HIGH,
    team: Team.MARKETING,
    dueDate: '2025-05-18',
    assignedTo: 'Ad Manager',
  },
  // Styleloom - video to be shoot
  {
    id: 't6',
    clientId: 'c10',
    title: 'Fashion Shoot',
    description: 'Video production for new collection.',
    status: Status.PENDING,
    priority: Priority.HIGH,
    team: Team.CREATIVE,
    dueDate: '2025-05-30',
    assignedTo: 'Video Team',
  },
  // Tangan Furniture - meeting
  {
    id: 't7',
    clientId: 'c11',
    title: 'Strategy Meeting',
    description: 'Quarterly review and planning meeting with client.',
    status: Status.PENDING,
    priority: Priority.MEDIUM,
    team: Team.MARKETING, // Meetings usually fall under account management/marketing
    dueDate: '2025-05-12',
    assignedTo: 'Account Mgr',
  },
  // MO Clinic - video shoot
  {
    id: 't8',
    clientId: 'c12',
    title: 'Clinic Promo Video',
    description: 'On-site video shoot for facility walkthrough.',
    status: Status.PENDING,
    priority: Priority.HIGH,
    team: Team.CREATIVE,
    dueDate: '2025-05-22',
    assignedTo: 'Video Team',
  },
  // synops labs - interview (marketing)
  {
    id: 't9',
    clientId: 'c13',
    title: 'Founder Interview',
    description: 'Record and edit interview for PR release.',
    status: Status.PENDING,
    priority: Priority.MEDIUM,
    team: Team.MARKETING,
    dueDate: '2025-05-28',
    assignedTo: 'Content Lead',
  },
  // Adding a few generic tasks for other clients to populate the board a bit
  {
    id: 't10',
    clientId: 'c1', // Bridgewater
    title: 'Q2 Performance Report',
    description: 'Compile analytics for Q2 review.',
    status: Status.COMPLETED,
    priority: Priority.LOW,
    team: Team.MARKETING,
    dueDate: '2025-04-30',
  },
  {
    id: 't11',
    clientId: 'c2', // Lets Fade
    title: 'Social Media Content',
    description: 'Design posts for Instagram.',
    status: Status.IN_PROGRESS,
    priority: Priority.MEDIUM,
    team: Team.CONTENT,
    dueDate: '2025-05-14',
  }
];
